import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { supabase } from '@/api/api'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

interface IPostsArray {
  posts: {
    data: [
      {
        id: string;
        title: string;
        description: string
        body: string
        created_at: string
      }
    ]
  }
}

export async function getStaticProps() {
  const posts = await supabase
    .from('posts')
    .select('*')

  return {
    props: {
      posts
    },
  }
}

export default function Home(posts: IPostsArray) {
  return (
    <>
      <Head>
        <title>DIO Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        <h1>DIO Blog</h1>
        { 
          posts.posts.data.map((post, index) => {
            return (
              <div key={index} className={styles.description}>
                <h2>{post.title}</h2>
                <hr />
                <h4>{post.description}</h4>
                <h3>{post.body}</h3>
              </div>
            )
          })
        }
      </main>
    </>
  )
}